name: CI
run-name: First Action
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Definir Variable
        run: echo "USERNAME=${{ github.actor }}" >> $GITHUB_ENV
      - name: Run script
        run: |
          python src/hola_mundo.py
