name: Multi-Job Python Workflow

on: [push]

jobs:
  job_generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Step 1 - Generate Data
        run: |
          echo "Hola desde job_generate!" > data.txt

      - name: Upload Data Artifact
        uses: actions/upload-artifact@v4
        with:
          name: data-file
          path: data.txt

  job_process:
    runs-on: ubuntu-latest
    needs: job_generate  # Indica que este job depende del anterior
    steps:
      - name: Download Data Artifact
        uses: actions/download-artifact@v4
        with:
          name: data-file

      - name: Step 2 - Process Data
        run: |
          python -c "with open('data.txt', 'r') as f: print('Job Process read:', f.read())"
