name: Parallel and Dependent Jobs Workflow

on: [push]

jobs:
  job_1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate Data 1
        run: echo "Hola desde job_1!" > data1.txt

      - name: Upload Data 1
        uses: actions/upload-artifact@v4
        with:
          name: data-file-1
          path: data1.txt

  job_2:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate Data 2
        run: echo "Hola desde job_2!" > data2.txt

      - name: Upload Data 2
        uses: actions/upload-artifact@v4
        with:
          name: data-file-2
          path: data2.txt

  job_3:
    runs-on: ubuntu-latest
    needs: ["job_1"]  # Asegúrate de que la sintaxis de 'needs' sea correcta
    steps:
      - name: Download Data 1
        uses: actions/download-artifact@v4
        with:
          name: data-file-1

      - name: Process Data 1
        run: |
        python -c "with open('data1.txt', 'r') as f: print('Job 3 read:', f.read())"

  job_4:
    runs-on: ubuntu-latest
    needs: ["job_2"]  # Corrige el formato de 'needs'
    steps:
      - name: Download Data 2
        uses: actions/download-artifact@v4
        with:
          name: data-file-2

      - name: Process Data 2
        run: |
        python -c "with open('data2.txt', 'r') as f: print('Job 4 read:', f.read())"
